insert into tasks (title, is_done, created_at) values ('Secret of the Grain, The (La graine et le mulet)', false, '2023-11-27');
insert into tasks (title, is_done, created_at) values ('Mackintosh Man, The', true, '2023-09-17');
insert into tasks (title, is_done, created_at) values ('English Surgeon, The', true, '2023-02-22');
insert into tasks (title, is_done, created_at) values ('Next Step, The', true, '2023-07-26');
insert into tasks (title, is_done, created_at) values ('Filth and Wisdom', false, '2023-07-02');
insert into tasks (title, is_done, created_at) values ('Don McKay', true, '2023-09-12');
insert into tasks (title, is_done, created_at) values ('Harry Potter and the Prisoner of Azkaban', false, '2023-09-25');
insert into tasks (title, is_done, created_at) values ('Death and the Maiden', false, '2023-05-26');
insert into tasks (title, is_done, created_at) values ('Rabbit Hole', true, '2023-11-03');
insert into tasks (title, is_done, created_at) values ('My Way', false, '2023-09-19');
insert into tasks (title, is_done, created_at) values ('Lady with the Dog, The (Dama s sobachkoy)', false, '2023-05-01');
insert into tasks (title, is_done, created_at) values ('Paziraie Sadeh', true, '2023-08-03');
insert into tasks (title, is_done, created_at) values ('Woman in the Meadow (Nainen kedolla)', false, '2023-05-04');
insert into tasks (title, is_done, created_at) values ('Zombie Lake (Lac des morts vivants, Le) (Zombies Lake) (Lake of the Living Dead, The)', false, '2023-12-14');
insert into tasks (title, is_done, created_at) values ('Pyx, The', false, '2023-12-08');
insert into tasks (title, is_done, created_at) values ('Soup to Nuts', true, '2024-01-11');
insert into tasks (title, is_done, created_at) values ('To Be Takei', true, '2023-07-06');
insert into tasks (title, is_done, created_at) values ('Case for Christ, The', true, '2023-07-21');
insert into tasks (title, is_done, created_at) values ('Into the Storm', true, '2023-06-09');
insert into tasks (title, is_done, created_at) values ('Little Princess, The', false, '2023-02-06');
insert into tasks (title, is_done, created_at) values ('Nick Offerman: American Ham', true, '2023-07-18');
insert into tasks (title, is_done, created_at) values ('End of St. Petersburg, The (Konets Sankt-Peterburga)', false, '2023-06-18');
insert into tasks (title, is_done, created_at) values ('Queen of Hearts', false, '2023-06-01');
insert into tasks (title, is_done, created_at) values ('Stray Dogs (Sag-haye velgard)', false, '2023-07-24');
insert into tasks (title, is_done, created_at) values ('Gold', false, '2024-01-03');
insert into tasks (title, is_done, created_at) values ('Tamara', false, '2023-01-14');
insert into tasks (title, is_done, created_at) values ('Legend of Zorro, The', false, '2023-09-24');
insert into tasks (title, is_done, created_at) values ('Dark and Stormy Night', false, '2023-08-04');
insert into tasks (title, is_done, created_at) values ('Highlander III: The Sorcerer (a.k.a. Highlander: The Final Dimension)', true, '2023-01-18');
insert into tasks (title, is_done, created_at) values ('Tevye', false, '2023-04-08');
insert into tasks (title, is_done, created_at) values ('That Lady in Ermine', true, '2023-10-07');
insert into tasks (title, is_done, created_at) values ('Rapt', false, '2023-04-29');
insert into tasks (title, is_done, created_at) values ('Naked Gun: From the Files of Police Squad!, The', false, '2023-04-06');
insert into tasks (title, is_done, created_at) values ('Presence, The', false, '2023-06-19');
insert into tasks (title, is_done, created_at) values ('Violeta Went to Heaven (Violeta se fue a los cielos)', true, '2023-01-23');
insert into tasks (title, is_done, created_at) values ('Frankenstein Unbound', true, '2023-11-06');
insert into tasks (title, is_done, created_at) values ('Taifu Club (Taifû kurabu)', false, '2023-07-24');
insert into tasks (title, is_done, created_at) values ('Tesseract, The', true, '2023-12-05');
insert into tasks (title, is_done, created_at) values ('Love & Human Remains', true, '2023-06-13');
insert into tasks (title, is_done, created_at) values ('Violence at Noon (Hakuchu no torima)', false, '2024-01-06');
insert into tasks (title, is_done, created_at) values ('History Boys, The', false, '2023-10-24');
insert into tasks (title, is_done, created_at) values ('Amistad', false, '2023-06-01');
insert into tasks (title, is_done, created_at) values ('Baby Face', true, '2023-12-04');
insert into tasks (title, is_done, created_at) values ('Danger! 50,000 Zombies', true, '2023-03-27');
insert into tasks (title, is_done, created_at) values ('House of Small Cubes, The (Tsumiki no ie)', true, '2024-01-03');
insert into tasks (title, is_done, created_at) values ('Alone (Issiz adam)', false, '2023-11-27');
insert into tasks (title, is_done, created_at) values ('Lavender Hill Mob, The', false, '2023-10-24');
insert into tasks (title, is_done, created_at) values ('Trumpet of the Swan, The', true, '2023-01-24');
insert into tasks (title, is_done, created_at) values ('Holidaze', true, '2023-02-28');
insert into tasks (title, is_done, created_at) values ('Inheritance, The (Karami-ai)', false, '2023-11-28');
